# Generated by Django 3.0 on 2020-02-11 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bincomapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='total_score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.CharField(max_length=50)),
                ('score', models.IntegerField()),
            ],
        ),
    ]
